### ISSUE TITLE
🌱 Reword "pulled image" in validation result details to "verified image"

### ISSUE THREAD

**Issue by TylerGillson** [validator-labs/validator-plugin-oci#242]
### Summary

The term "pulled" is misleading, since we don't actually pull the entire image, just its metadata.

Also, the README says the plugin _does_ support optionally pulling the image... so we need to either implement that or update both the README and the inline help text in the validatorctl TUI.

**Comment by ahmad-ibra** [comment]
There shouldn't be anything to do for this issue.

The following is done in order:
1. a head request is made to check for the existence of the artifact
2. the artifact is pulled and stored in the `img` var in memory (to be eventually garbage collected)
3. the artifact is validated

Below is the code showing this:
https://github.com/validator-labs/validator-plugin-oci/blob/d39fc6dd08a0a847518fafb40a74e6e9ffb0de9c/pkg/oci/oci.go#L100-L120

**Comment by ahmad-ibra** [comment]
@TylerGillson feel free to re-open if you disagree for any reason

**Comment by TylerGillson** [comment]
@ahmad-ibra requesting the following changes:
- We should only pull the image if full layer validation is enabled (and this should be documented in an API docstring)
- The detail messages should only state "pulled" in the above case, otherwise they should say "verified"
